---
- hosts: awx
  gather_facts: yes
  vars_files:
    - ./vars.yml
  tasks:
    - name: Install Python and Pip
      apt:
        update_cache: yes
        pkg:
          - python3
          - python3-pip
      become: True

    - name: Upgrade Pip
      pip: 
        name: pip
        extra_args: --upgrade
      become: no

    - name: Install docker
      import_role:
        name: geerlingguy.docker

    - name: Install pip dependencies
      pip:
        name:
          - docker
          - docker-compose

    - name: Create the external docker network
      docker_network:
        name: '{{external_network}}'
        state: present
        ipam_config:
          - subnet: 172.200.0.0/16
            gateway: 172.200.0.1
            iprange: 172.200.0.0/16

    - name: Boot up the PostgreSQL database
      import_role:
        name: conatel_digital_hub.run_postgres

    - name: Boot up the AWX service
      import_role:
        name: conatel_digital_hub.run_awx
